// SPDX-License-Identifier: GPL-3.0-only
// Copyright (c) 2026, Christoph Gaffga
//
// Raw FFI bindings for cgaffga/phasm-openh264 wels_stego.h C ABI.
//
// Pinned to upstream tag `phasm-stego-v0.1.0` (commit 5d657c83). The
// underlying C++ library is BSD-2-Clause (OpenH264 v2.6.0 base + phasm
// stego additions). See vendor/phasm-openh264/codec/api/wels/wels_stego.h
// for the canonical C API documentation.
//
// Bindings are hand-written rather than generated by bindgen so the
// ABI surface stays auditable. The wels_stego.h surface is tiny:
//   - 1 enum (PhasmStegoDomain)
//   - 2 plain-data structs (PhasmStegoPos, PhasmStegoMdCost)
//   - 3 callback function types
//   - 1 callback table struct (PhasmStegoCallbacks)
//   - 3 entry points (register, set-frame-num, abi-version)
//
// Higher-level Rust API (registration RAII guard, panic catching in
// callbacks, position-key conversion) lives in phasm-core (Phase B.4).

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

use core::ffi::c_void;

/// ABI version this header was compiled against. Matches the value
/// returned by `WelsStegoAbiVersion()` on a current build of the fork.
///
/// 1.3.1 (#533.2) widens `PhasmStegoMbDecision::ui_mb_type` from u8
/// to u16 so the field can faithfully hold OH264's `Mb_Type`
/// bitfield (values up to MB_TYPE_DIRECT=0x800, MB_TYPE_P1L1=0x8000).
/// Reorder keeps the struct at 180 bytes. Phasm 1.3.0 had a u8
/// field that couldn't represent MB_TYPE_SKIP=0x100 — caught before
/// any consumer shipped against 1.3.0.
/// 1.3.0 (#533 Phase 1) adds Pass-2 replay: `capture_mb_decision` +
/// `replay_mb_decision` callbacks + `WelsStegoSetPassMode()`. Pass-1
/// streams per-MB mode decisions into a phasm-side cache; Pass-2
/// fetches them back, bypassing the encoder's RDO/ME and locking the
/// two passes onto the same mode-decision domain.
/// 1.2.0 (Phase C.8.2) adds the `dual_recon_observe` callback that
/// fires from the internal `phasm_dual_recon_writeback` helper once
/// it commits clean pixels to pDecPic and stego pixels to
/// pVisualRecPic. Used by cascade-verify + PSNR tests + visual debug.
/// 1.1.0 (Phase A.5(j)) wired `md_cost_capture` in the encoder. The
/// callback fires once per MB after mode decision finalizes, carrying
/// a `PHASM_MB_TYPE_*` classification byte the consumer uses to filter
/// pre-emit fires by `block_cat` ↔ `mb_type` consistency.
pub const PHASM_STEGO_ABI_VERSION: u32 = 0x0001_0301;

/// PhasmStegoMdCost::mb_type classifications. Match the C
/// `PHASM_MB_TYPE_*` defines in `wels_stego.h`. Each value names the
/// shape of the EMITTED residual:
///
///   - `PHASM_MB_TYPE_I_4x4`   : keep block_cat ∈ {2, 3, 4}
///   - `PHASM_MB_TYPE_I_16x16` : keep block_cat ∈ {0, 1, 3, 4}
///   - `PHASM_MB_TYPE_I_8x8`   : keep block_cat ∈ {5, 3, 4} (High-profile)
///   - `PHASM_MB_TYPE_INTER`   : keep block_cat ∈ {2, 3, 4}
///   - `PHASM_MB_TYPE_SKIP`    : drop ALL coefficient hook fires
///   - `PHASM_MB_TYPE_OTHER`   : unknown shape, conservative: keep all
pub const PHASM_MB_TYPE_I_4x4: u8 = 0;
pub const PHASM_MB_TYPE_I_16x16: u8 = 1;
pub const PHASM_MB_TYPE_I_8x8: u8 = 2;
pub const PHASM_MB_TYPE_INTER: u8 = 3;
pub const PHASM_MB_TYPE_SKIP: u8 = 4;
pub const PHASM_MB_TYPE_OTHER: u8 = 5;

/// Return true if a hook fire with the given `block_cat` is wire-bound
/// when the containing MB committed to `mb_type`. Used to filter the
/// 4-domain `enc_pre_emit` fire stream down to wire-aligned positions
/// (the stream includes RDO simulation candidates whose block_cats do
/// NOT match the winning mode).
#[inline]
pub fn block_cat_matches_mb_type(mb_type: u8, block_cat: u8) -> bool {
    match mb_type {
        PHASM_MB_TYPE_SKIP => false,
        PHASM_MB_TYPE_I_16x16 => matches!(block_cat, 0 | 1 | 3 | 4),
        PHASM_MB_TYPE_I_4x4 => matches!(block_cat, 2 | 3 | 4),
        PHASM_MB_TYPE_I_8x8 => matches!(block_cat, 5 | 3 | 4),
        PHASM_MB_TYPE_INTER => matches!(block_cat, 2 | 3 | 4),
        _ => true, // unknown classification → conservative
    }
}

// ---------------------------------------------------------------------
// Phase B.8 — encoder hook key ↔ phasm walker key translation
//
// Spec references:
//   * H.264 § 6.5.1     — 4×4 zigzag scan
//   * H.264 § 6.4.3     — macroblock 4×4 block scan order
//   * H.264 § 9.3.3.2   — CABAC residual block parse direction
//                         (last-significant-first → reverse scan)
//
// CRITICAL CONTRACT — assumes OpenH264 v2.6.0 encoder defaults:
//   * uiProfileIdc may be PRO_HIGH but the encoder source has zero
//     8×8-transform implementation (Transform8x8/Quantization8x8/
//     DCT8x8 don't exist). `transform_8x8_mode_flag` defaults to 0
//     in PPS emission. ⇒ BC=5 (Luma8x8) never fires from this
//     encoder → translation returns None for it.
//   * Frame coding only (no field/interlaced).
//   * iMultipleThreadIdc=1 (the Rust trampoline is single-threaded
//     today; multi-thread = future #339).
//   * CABAC entropy coding (iEntropyCodingModeFlag=1). CAVLC encode
//     works at the hook level but the phasm walker is CABAC-only.
//
// Phasm walker `PositionKey` layout (must stay in sync with
// `core/src/codec/h264/stego/hook.rs:200-258`):
//   * bits 0..23   frame_idx
//   * bits 24..47  mb_addr     (= mb_y * mb_width + mb_x)
//   * bits 48..51  EmbedDomain (0=CoeffSignBypass, 1=CoeffSuffixLsb)
//   * bits 52..63  SyntaxPath  (3-bit variant tag + 9-bit payload)
//
// SyntaxPath pack format per `hook.rs:117-156`:
//   tag 0  Luma4x4           payload = block_idx(4) | coeff_idx(4)<<4 | kind(1)<<8
//   tag 2  ChromaAc          payload = plane(1) | block_idx(2)<<1 | coeff_idx(4)<<3 | kind(1)<<7
//   tag 3  ChromaDc          payload = plane(1) | coeff_idx(2)<<1 | kind(1)<<3
//   tag 4  LumaDcIntra16x16  payload = coeff_idx(4) | kind(1)<<4
// ---------------------------------------------------------------------

/// H.264 4×4 zigzag scan (spec § 6.5.1): scan_index → raster_index.
pub const ZZ_SCAN_4X4: [u8; 16] = [
    0, 1, 4, 8, 5, 2, 3, 6, 9, 12, 13, 10, 7, 11, 14, 15,
];

/// Inverse of `ZZ_SCAN_4X4`: raster_index → scan_index. Lets us
/// translate an encoder hook's raster `coeff_idx` into the walker's
/// scan-order `coeff_idx`.
pub const INV_ZZ_SCAN_4X4: [u8; 16] = [
    0, 1, 5, 6, 2, 4, 7, 12, 3, 8, 11, 13, 9, 10, 14, 15,
];

/// Compile-time consistency check between the two tables (panic
/// at `cargo build` time if they ever drift).
const _: () = {
    let mut i = 0u8;
    while i < 16 {
        if INV_ZZ_SCAN_4X4[ZZ_SCAN_4X4[i as usize] as usize] != i {
            panic!("ZZ_SCAN_4X4 / INV_ZZ_SCAN_4X4 mismatch — fix tables");
        }
        i += 1;
    }
};

/// Translate an encoder hook position into the canonical phasm
/// `PositionKey` raw u64 that the walker emits for the same physical
/// coefficient. Returns `None` for positions that are not coefficient
/// signs / suffix-LSBs of a wire-bound block_cat (BC=5 Luma8x8, MVD
/// domains, sim-fire positions where the MB picked a different mode).
///
/// The function is pure (no shared state), so it's thread-safe for
/// multi-thread encode use cases. Cost: one table lookup + one bit
/// packing per call (~5–10 ns).
///
/// Consumer pattern:
/// ```ignore
/// // Pass 1 capture
/// for fire in encoder_fires {
///     if let Some(key) = encoder_pos_to_phasm_position_key(
///         &fire.pos, mb_type_table[fire.mb_addr], mb_width) {
///         cover[walker_idx_for[key]] = fire.bit;
///     }
/// }
/// ```
pub fn encoder_pos_to_phasm_position_key(
    pos: &PhasmStegoPos,
    mb_type: u8,
    mb_width: u32,
) -> Option<u64> {
    // MVD domains (2 = MvdSign, 3 = MvdSuffixLsb) take a separate
    // packing path: the walker emits SyntaxPath::Mvd { list, partition,
    // axis, kind } and the fork's HOOK-H1..H7 fire with mv_component
    // + partition_idx populated, block_cat = 0xff (no residual block).
    // Skip the coefficient block_cat filter and pack via the Mvd arm.
    if pos.domain >= 2 {
        return encoder_mvd_pos_to_phasm_position_key(pos, mb_width);
    }
    // Domain enum value mapping (coefficient domains):
    //   PhasmStegoDomain::CoeffSuffixLsb = 0  →  phasm EmbedDomain::CoeffSuffixLsb  = 1
    //   PhasmStegoDomain::CoeffSign      = 1  →  phasm EmbedDomain::CoeffSignBypass = 0
    // BinKind: Sign = 0, SuffixLsb = 1.
    let phasm_domain: u8 = if pos.domain == 1 { 0 } else { 1 };
    let bin_kind: u16 = if pos.domain == 1 { 0 } else { 1 };

    // Filter sim-fire positions: only keep fires whose block_cat
    // matches the MB's committed winning mode.
    if !block_cat_matches_mb_type(mb_type, pos.block_cat) {
        return None;
    }

    // Per-block_cat → phasm SyntaxPath packing. Encoder hook firing
    // conventions verified empirically against fork at commit
    // acf7db39 (see openh264_b8_design_2026_05_11.md).
    let syntax_packed: u16 = match pos.block_cat {
        // BC=0  — I_16x16 LumaDC (HOOK-A, "post-quant pre-scan")
        //   Encoder fires: sub_block = raster 0..15, coeff_idx = 0.
        //   Walker: SyntaxPath::LumaDcIntra16x16 { coeff_idx = scan 0..15 }.
        //   Map sub_block raster → spec scan via INV_ZZ_SCAN.
        0 => {
            let scan_ci = INV_ZZ_SCAN_4X4[pos.sub_block as usize & 0xF] as u16;
            let payload = (scan_ci & 0xF) | ((bin_kind & 0x1) << 4);
            4u16 | (payload << 3) // tag 4 = LumaDcIntra16x16
        }
        // BC=1  — I_16x16 LumaAC (HOOK-B, "post-quant pre-scan")
        //   Encoder fires: sub_block = MB-scan index 0..15 (strip-major
        //     iteration `i*4+phasm_sb` matches spec quadrant ordering),
        //     coeff_idx = raster 1..15 (DC slot 0 skipped).
        //   Walker `decode_residual_block_with_null_logger(0, 14, cat=1)`
        //     reads 15 AC coefs at scan_AC indices 0..14 (= spec scan
        //     positions 1..15, offset by -1).
        //   Map: walker.coeff_idx = INV_ZZ_SCAN[enc.coeff_idx] - 1.
        1 => {
            let block_idx = pos.sub_block as u16 & 0xF;
            let spec_scan = INV_ZZ_SCAN_4X4[pos.coeff_idx as usize & 0xF] as u16;
            if spec_scan == 0 {
                // raster=0 would map to spec scan 0 (DC slot), which
                // BC=1 shouldn't emit. Defensive guard.
                return None;
            }
            let scan_ci = spec_scan - 1; // 0..14 walker AC indexing
            let payload = block_idx
                | ((scan_ci & 0xF) << 4)
                | ((bin_kind & 0x1) << 8);
            0u16 | (payload << 3) // tag 0 = Luma4x4
        }
        // BC=2  — Luma 4×4, I_4x4 + inter (HOOK-E, HOOK-F)
        //   Encoder fires: sub_block = MB-scan 0..15, coeff_idx = raster
        //     0..15 (HOOK-E is "pre-scan"; HOOK-F is "post-scan" with
        //     dual-write — both reach this BC=2 path, the position
        //     field is filled with raster in both cases per the helpers
        //     in svc_encode_mb.cpp).
        //   Walker `decode_residual_block_with_null_logger(0, 15, cat=2)`
        //     reads 16 coefs at scan indices 0..15.
        //   Map: walker.coeff_idx = INV_ZZ_SCAN[enc.coeff_idx].
        //
        //   NOTE: HOOK-F's dual-write actually fires with `coeff_idx_scanned`
        //   already in scan order per its comment ("post-quant POST-scan").
        //   We may need a separate path here once we exercise inter
        //   content; for IDR-only fixture, BC=2 = HOOK-E only.
        //   TODO inter validation: probe a P-frame fixture and verify
        //   BC=2 from HOOK-F still matches with INV_ZZ_SCAN applied.
        2 => {
            let block_idx = pos.sub_block as u16 & 0xF;
            let scan_ci = INV_ZZ_SCAN_4X4[pos.coeff_idx as usize & 0xF] as u16;
            let payload = block_idx
                | ((scan_ci & 0xF) << 4)
                | ((bin_kind & 0x1) << 8);
            0u16 | (payload << 3) // tag 0 = Luma4x4
        }
        // BC=3  — Chroma DC (HOOK-C, 2×2 Hadamard, 4 entries per plane)
        //   Encoder fires: partition_idx = iUV-1 (0=Cb, 1=Cr) — plane
        //     lives HERE, NOT in sub_block. sub_block = 0 always.
        //     coeff_idx = 0..3 (Hadamard order).
        //   Walker `decode_residual_block_with_null_logger(0, 3, cat=3)`
        //     reads 4 DC coefs at coeff_idx 0..3.
        //   Map: walker.plane = enc.partition_idx, walker.coeff_idx =
        //     enc.coeff_idx (direct, no scan transform).
        3 => {
            let plane = pos.partition_idx as u16 & 0x1;
            let scan_ci = pos.coeff_idx as u16 & 0x3;
            let payload = plane
                | (scan_ci << 1)
                | ((bin_kind & 0x1) << 3);
            3u16 | (payload << 3) // tag 3 = ChromaDc
        }
        // BC=4  — Chroma AC (HOOK-D / HOOK-G, "post-quant POST-scan")
        //   Encoder fires: partition_idx = iUV-1 (0=Cb, 1=Cr) — plane
        //     lives HERE, NOT in sub_block. sub_block = block_idx 0..3
        //     within plane. coeff_idx = phasm_s = scanned index 0..14
        //     (HOOK-G is "POST-scan" — already in walker order).
        //   Walker `decode_residual_block_with_null_logger(0, 14, cat=4)`
        //     reads 15 AC coefs at coeff_idx 0..14.
        //   Map: walker.plane = enc.partition_idx, walker.block_idx =
        //     enc.sub_block, walker.coeff_idx = enc.coeff_idx (direct).
        4 => {
            let plane = pos.partition_idx as u16 & 0x1;
            let block_idx = pos.sub_block as u16 & 0x3;
            let scan_ci = pos.coeff_idx as u16 & 0xF;
            let payload = plane
                | (block_idx << 1)
                | ((scan_ci & 0xF) << 3)
                | ((bin_kind & 0x1) << 7);
            2u16 | (payload << 3) // tag 2 = ChromaAc
        }
        // BC=5: Luma 8×8 — dead code from OpenH264 v2.6.0 encoder.
        // See the CRITICAL CONTRACT header comment above.
        _ => return None,
    };

    let mb_addr = (pos.mb_y as u32) * mb_width + (pos.mb_x as u32);
    let frame_bits = (pos.frame_num as u64) & 0xFF_FFFF;
    let mb_bits = ((mb_addr as u64) & 0xFF_FFFF) << 24;
    let domain_bits = ((phasm_domain as u64) & 0xF) << 48;
    let syntax_bits = ((syntax_packed as u64) & 0xFFF) << 52;
    Some(frame_bits | mb_bits | domain_bits | syntax_bits)
}

/// MVD-domain canonical-key packer (`PhasmStegoDomain::MvdSign` /
/// `MvdSuffixLsb`). Mirrors the walker's `SyntaxPath::Mvd { list,
/// partition, axis, kind }` packing in `core/src/codec/h264/stego/hook.rs`.
///
/// Fork-side hook source (`codec/encoder/core/src/wels_stego.cpp::
/// phasm_apply_mvd_hooks`) populates `PhasmStegoPos` per emitted
/// MVD bin as follows:
///
/// - `mb_x`, `mb_y` — current MB scan position.
/// - `partition_idx` — H.264-spec partition_id =
///   mbPartIdx*4 + subMbPartIdx (per #549 Bug 5, 2026-05-19). The
///   walker emits the same convention in `decode_sub_mb_mvds`'s `p()`
///   helper (and after the slice.rs fix for the P_16x8 / P_8x16 sites)
///   so the encoder and walker key on identical values.
///   Examples:
///     - P_16x16:  0
///     - P_16x8:   0 (top),     4 (bottom)
///     - P_8x16:   0 (left),    4 (right)
///     - P_8x8 SUB_8x8: i*4  ∈ {0, 4, 8, 12}
///     - P_8x8 SUB_8x4: i*4+j ∈ {0,1, 4,5, 8,9, 12,13}
///     - P_8x8 SUB_4x8: i*4+j ∈ {0,1, 4,5, 8,9, 12,13}
///     - P_8x8 SUB_4x4: i*4+j ∈ {0..15}
/// - `mv_component` — 0 = X axis, 1 = Y axis.
/// - `domain` — 2 = MvdSign, 3 = MvdSuffixLsb.
/// - `sub_block`, `coeff_idx`, `block_cat` — set to 0xff (MVD doesn't
///   use these). `ref_idx` carries the L0 reference index but isn't
///   part of the canonical key.
///
/// `mb_type` is not consulted: the encoder only fires MVD hooks from
/// HOOK-H1..H7 after the MB's mb_type is decided, so the filter would
/// always pass for the emitted positions.
///
/// OH264 fork is **P-slice only** for MVD writes — `list` is always 0
/// (LIST_0). The function masks to 1 bit to stay future-proof if/when
/// the fork grows B-slice support and the hook populates list_idx.
fn encoder_mvd_pos_to_phasm_position_key(pos: &PhasmStegoPos, mb_width: u32) -> Option<u64> {
    // Fork enum → walker enum is identity for MVD:
    //   PhasmStegoDomain::MvdSign      = 2  →  EmbedDomain::MvdSignBypass = 2
    //   PhasmStegoDomain::MvdSuffixLsb = 3  →  EmbedDomain::MvdSuffixLsb  = 3
    let phasm_domain: u8 = pos.domain;
    // BinKind: Sign = 0 (MvdSign), SuffixLsb = 1 (MvdSuffixLsb).
    let bin_kind: u16 = if pos.domain == 2 { 0 } else { 1 };

    // SyntaxPath::Mvd packing (walker, `hook.rs:148`):
    //   payload = list(1) | partition(4) << 1 | axis(1) << 5 | kind(1) << 6
    //   syntax_packed = 5 | (payload << 3)
    //
    // `list` is the high nibble of partition_idx on the decoder hook
    // side per `parse_mb_syn_cabac.cpp:1246-1247`
    // (`partition_idx = ((list << 4) | (index & 0x0F))`). Mirror that
    // on encoder: low nibble = partition, high nibble = list. The
    // fork's `phasm_apply_mvd_hooks` currently passes partition_idx
    // raw (no list nibble) per `wels_stego.cpp:313`, so list = 0 for
    // every P-slice fire. If a future fork patch adds B-slice MVD
    // writes it should adopt the same `(list << 4) | partition`
    // convention as the decoder hook.
    let list = ((pos.partition_idx >> 4) & 0x1) as u16;
    let partition = (pos.partition_idx & 0xF) as u16;
    let axis = (pos.mv_component & 0x1) as u16;
    let payload = list | (partition << 1) | (axis << 5) | ((bin_kind & 0x1) << 6);
    let syntax_packed: u16 = 5 | (payload << 3);

    let mb_addr = (pos.mb_y as u32) * mb_width + (pos.mb_x as u32);
    let frame_bits = (pos.frame_num as u64) & 0xFF_FFFF;
    let mb_bits = ((mb_addr as u64) & 0xFF_FFFF) << 24;
    let domain_bits = ((phasm_domain as u64) & 0xF) << 48;
    let syntax_bits = ((syntax_packed as u64) & 0xFFF) << 52;
    Some(frame_bits | mb_bits | domain_bits | syntax_bits)
}

// ---------------------------------------------------------------------
// 1. Stego domain enum
//
// `#[repr(u8)]` matches the C `uint8_t domain` field in
// `PhasmStegoPos`. The integer values are part of the ABI; do not
// renumber.
// ---------------------------------------------------------------------

#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PhasmStegoDomain {
    /// LSB of EG suffix when `|level| >= 15`.
    CoeffSuffixLsb = 0,
    /// Sign bit of each non-zero quantized coefficient.
    CoeffSign = 1,
    /// Sign bit of each non-zero MVD component (x or y).
    MvdSign = 2,
    /// LSB of EG suffix when `|MVD component| >= 9`.
    MvdSuffixLsb = 3,
}

impl PhasmStegoDomain {
    /// Translate a raw `u8` from the position descriptor into the typed
    /// enum. Returns `None` for unknown values (forward-compat with
    /// future MAJOR ABI bumps).
    #[inline]
    pub fn from_u8(value: u8) -> Option<Self> {
        match value {
            0 => Some(Self::CoeffSuffixLsb),
            1 => Some(Self::CoeffSign),
            2 => Some(Self::MvdSign),
            3 => Some(Self::MvdSuffixLsb),
            _ => None,
        }
    }
}

/// Number of stego domains (matches `PHASM_DOMAIN__COUNT_` in C).
pub const PHASM_DOMAIN_COUNT: usize = 4;

// ---------------------------------------------------------------------
// 2. Position descriptor (16 bytes, fixed layout)
//
// Identifies a single candidate stego bin in (frame, MB, partition,
// sub-block, coefficient/MV-component) space. See wels_stego.h for the
// per-domain field validity table.
// ---------------------------------------------------------------------

#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct PhasmStegoPos {
    pub frame_num: u32,
    pub mb_x: u16,
    pub mb_y: u16,
    pub domain: u8,
    pub partition_idx: u8,
    pub sub_block: u8,
    pub coeff_idx: u8,
    pub block_cat: u8,
    pub ref_idx: u8,
    pub mv_component: u8,
    pub _reserved: u8,
}

// Compile-time guarantee that the Rust layout matches the C ABI's 16-byte
// fixed size. Catches accidental field-type/-order changes at build time.
const _: () = assert!(core::mem::size_of::<PhasmStegoPos>() == 16);

// ---------------------------------------------------------------------
// 3. Mode-decision cost descriptor
//
// One per MB, fired after mode decision finalizes. Carries chosen
// mb_type + per-domain capacity estimates for STC planning.
// ---------------------------------------------------------------------

#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct PhasmStegoMdCost {
    pub frame_num: u32,
    pub mb_x: u16,
    pub mb_y: u16,
    pub mb_type: u8,
    pub cbp: u8,
    pub _reserved: u16,
    pub capacity: [u16; PHASM_DOMAIN_COUNT],
}

const _: () = assert!(core::mem::size_of::<PhasmStegoMdCost>() == 20);

// ---------------------------------------------------------------------
// 4-6. Callback function types
//
// `Option<extern "C" fn(...)>` is the standard Rust representation for
// nullable C function pointers (the `Option` is FFI-safe per the
// std::option docs: it has the same layout as the inner non-null fn
// pointer plus a niche for None=NULL).
// ---------------------------------------------------------------------

/// Encoder pre-emit callback. Return -1 for no override (emit
/// `original`), or 0/1 to override with that bit. Any other return
/// value is treated as -1.
pub type PhasmStegoEncPreEmitFn =
    Option<unsafe extern "C" fn(pos: *const PhasmStegoPos, original: i32, user_data: *mut c_void) -> i32>;

/// Decoder post-read callback. Pure observation; no return value.
pub type PhasmStegoDecPostReadFn =
    Option<unsafe extern "C" fn(pos: *const PhasmStegoPos, bit_value: i32, user_data: *mut c_void)>;

/// Mode-decision cost-capture callback. Pure observation; no return.
pub type PhasmStegoMdCostFn =
    Option<unsafe extern "C" fn(cost: *const PhasmStegoMdCost, user_data: *mut c_void)>;

/// Dual-recon observation callback. Fires from the internal
/// `phasm_dual_recon_writeback` helper after both clean and stego
/// pixel blocks have been committed to their respective recon
/// pictures (pDecPic + pVisualRecPic). Pure observation; no return.
///
/// The `clean_pixels` and `stego_pixels` pointers are valid for the
/// duration of the callback only; copy if needed beyond.
/// `src_stride` is the byte distance between consecutive rows of both
/// source blocks (typically equals `block_w`).
pub type PhasmStegoDualReconFn = Option<
    unsafe extern "C" fn(
        frame_num: u32,
        mb_x: u16,
        mb_y: u16,
        plane: u8,
        pixel_x: i32,
        pixel_y: i32,
        block_w: i32,
        block_h: i32,
        clean_pixels: *const u8,
        stego_pixels: *const u8,
        src_stride: i32,
        user_data: *mut c_void,
    ),
>;

// ---------------------------------------------------------------------
// 6.7 Pass-2 replay architecture
//
// `PhasmStegoMbDecision` is the per-MB cache record. Pass-1 captures
// the encoder's finalized mode decisions; Pass-2 replays from this
// cache and skips RDO/ME entirely. Layout must match the C
// `PhasmStegoMbDecision` struct byte-for-byte.
// See: docs/design/video/h264/pass2-replay-architecture.md
// ---------------------------------------------------------------------

/// Encoder pass mode. CAPTURE = Pass-1 (RDO/ME runs, capture
/// callback fires per MB). REPLAY = Pass-2 (replay callback supplies
/// cached decision per MB, encoder skips RDO/ME).
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PhasmStegoPassMode {
    Passthrough = 0,
    Capture = 1,
    Replay = 2,
}

#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct PhasmStegoMbDecision {
    pub frame_num: u32,
    pub mb_x: u16,
    pub mb_y: u16,

    /// OH264-internal `Mb_Type` bitfield value (lower 16 bits). For
    /// baseline + Main-profile flags through MB_TYPE_P1L1 (0x8000),
    /// this field captures the encoder's MB type verbatim — Pass-2
    /// replay writes it back to `pCurMb->uiMbType` directly.
    pub ui_mb_type: u16,
    pub mb_type: u8,
    pub qp_delta: i8,
    pub sub_mb_type: [u8; 4],

    pub mv_x: [[i16; 2]; 16],
    pub mv_y: [[i16; 2]; 16],
    pub ref_idx: [[i8; 2]; 4],
    pub bipred_dir: [u8; 4],

    pub intra16_pred_mode: u8,
    pub i4x4_pred_mode: [u8; 16],
    pub chroma_pred_mode: u8,

    pub _reserved: [u8; 6],
}

// Compile-time guarantee that the Rust layout matches the C side's
// fixed record. Catches accidental field reorders / type changes.
// Size = 8 (id) + 8 (top-level) + 128 (motion) + 12 (ref+bipred) + 18
// (intra) + 6 (reserved) = 180 bytes (max field align = 4, no tail pad).
const _: () = assert!(core::mem::size_of::<PhasmStegoMbDecision>() == 180);

/// Pass-1 capture callback. Fires per MB after mode decision
/// finalizes. Consumer copies `decision` into its own cache keyed
/// by (frame_num, mb_x, mb_y). The pointer is valid only for the
/// call duration.
pub type PhasmStegoCaptureMbDecisionFn =
    Option<unsafe extern "C" fn(decision: *const PhasmStegoMbDecision, user_data: *mut c_void)>;

/// Pass-2 replay callback. Fires at the start of each MB's mode
/// decision. Consumer fills `*out_decision` with the cached decision
/// and returns 1; returns 0 on cache miss (encoder falls back to
/// running RDO/ME).
pub type PhasmStegoReplayMbDecisionFn = Option<
    unsafe extern "C" fn(
        frame_num: u32,
        mb_x: u16,
        mb_y: u16,
        out_decision: *mut PhasmStegoMbDecision,
        user_data: *mut c_void,
    ) -> i32,
>;

// ---------------------------------------------------------------------
// 7. Callback table
//
// `struct_size` MUST equal `size_of::<PhasmStegoCallbacks>()`. The
// fork registration function rejects mismatches outright — phasm
// owns both sides of this boundary (fork + bindings ship together)
// so there is no version-tolerance path.
// ---------------------------------------------------------------------

#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct PhasmStegoCallbacks {
    pub struct_size: usize,
    pub enc_pre_emit: PhasmStegoEncPreEmitFn,
    pub dec_post_read: PhasmStegoDecPostReadFn,
    pub md_cost_capture: PhasmStegoMdCostFn,
    pub dual_recon_observe: PhasmStegoDualReconFn,
    pub capture_mb_decision: PhasmStegoCaptureMbDecisionFn,
    pub replay_mb_decision: PhasmStegoReplayMbDecisionFn,
}

impl Default for PhasmStegoCallbacks {
    fn default() -> Self {
        Self {
            struct_size: core::mem::size_of::<Self>(),
            enc_pre_emit: None,
            dec_post_read: None,
            md_cost_capture: None,
            dual_recon_observe: None,
            capture_mb_decision: None,
            replay_mb_decision: None,
        }
    }
}

// ---------------------------------------------------------------------
// 8-10. Extern "C" entry points
// ---------------------------------------------------------------------

unsafe extern "C" {
    /// Register process-global callbacks. Pass `null` for `callbacks`
    /// to reset (no hooks). `user_data` is passed back to each callback
    /// unchanged; caller owns lifetime.
    ///
    /// Returns 0 on success, non-zero on ABI mismatch (e.g. struct_size
    /// older than the library's minimum supported version).
    ///
    /// # Safety
    /// `callbacks` (if non-null) must point to a valid
    /// `PhasmStegoCallbacks` with `struct_size` set to
    /// `size_of::<PhasmStegoCallbacks>()`. `user_data` is opaque to the
    /// library — the caller is responsible for ensuring it outlives the
    /// registration.
    pub fn WelsRegisterPhasmStegoCallbacks(
        callbacks: *const PhasmStegoCallbacks,
        user_data: *mut c_void,
    ) -> i32;

    /// Set the current frame number. Goes into every `PhasmStegoPos` +
    /// `PhasmStegoMdCost` delivered to callbacks for that frame. Reset
    /// to 0 at the start of each new encode/decode session.
    pub fn WelsStegoSetFrameNum(frame_num: u32);

    /// Build-time sanity check that the linked fork matches these
    /// bindings. Returns `PHASM_STEGO_ABI_VERSION` from the fork.
    pub fn WelsStegoAbiVersion() -> u32;

    /// Set the encoder's pass mode for the next encode() call.
    /// Caller selects per-pass: PASSTHROUGH (default, no
    /// capture/replay), CAPTURE (Pass-1, capture callback fires),
    /// REPLAY (Pass-2, replay callback fetches cached decisions).
    pub fn WelsStegoSetPassMode(mode: PhasmStegoPassMode);

    /// Phase 4.5.b (#538) — wire-only override mode gate.
    ///
    /// When enabled (non-zero), the mutating-hook helpers route
    /// stego override decisions into the per-MB bypass-bin scratch
    /// table (read by `phasm_apply_bypass_bin_override` at CABAC
    /// emit) and DO NOT mutate the encoder's stored `*level` / MV
    /// state. Pass-2's pDecPic stays byte-identical to Pass-1's,
    /// and the stego override only manifests on the wire via the
    /// bypass-bin emit hooks. Phase 4.5.d aligns populate-side and
    /// emit-side keys via raster↔scan reconciliation so all 4
    /// stego domains × all 5 block_cats fire correctly under
    /// flag ON.
    ///
    /// Default OFF. Set to non-zero before encoding to opt into
    /// the wire-only path. Phase 5 (#539) flips the default once
    /// the C.8.x dual-recon machinery is deleted.
    pub fn phasm_set_use_wire_only_overrides(enabled: i32);

    /// Read the current wire-only flag state.
    pub fn phasm_get_use_wire_only_overrides() -> i32;

    /// #548 v1.0 BLOCKER fix (2026-05-18) — Reset libencoder-side
    /// phasm statics at the start of a new encode session. Resets the
    /// bypass scratch table, the last-MB sentinels, and the
    /// wire-only flag. Call at the top of every
    /// `h264_encode_gop_framed_bits_auto` invocation so two
    /// consecutive calls don't share fork state.
    pub fn phasm_reset_encoder_session_state();

    /* Phase 4.6 NEGATIVE-result diagnostic counters (#538). Track
     * scratch writes / reads / hits / resets to bisect the
     * forged-flip-doesn't-propagate bug. Removed once 4.6 closes. */
    pub fn phasm_diag_get_set_calls() -> u64;
    pub fn phasm_diag_get_set_writes() -> u64;
    pub fn phasm_diag_get_set_rejected_oob() -> u64;
    pub fn phasm_diag_get_apply_calls() -> u64;
    pub fn phasm_diag_get_apply_hits() -> u64;
    pub fn phasm_diag_get_reset_calls() -> u64;
    pub fn phasm_diag_reset_counters();

    // ----- Phase C.8.13(b) debug counters (#455) ------------------------
    // Read/reset atomic counters tracking phasm_apply_coeff_hooks_dual
    // outcomes. Used by the cascade-gap audit to confirm whether the
    // residual leak comes from the `*level_a != *level_b` precondition.
    // -------------------------------------------------------------------

    /// Total dual-write fires that entered the helper (passed null +
    /// callback-registered gates).
    pub fn phasm_get_hook_dual_fires_total() -> u64;

    /// Bails on `*level_a == 0` (early-out for zero-coefficient positions).
    pub fn phasm_get_hook_dual_bail_level_a_zero() -> u64;

    /// Bails on `*level_a != *level_b` (precondition mismatch).
    pub fn phasm_get_hook_dual_bail_level_mismatch() -> u64;

    /// Successful applies (helper wrote a new_level).
    pub fn phasm_get_hook_dual_applied() -> u64;

    /// Reset all dual + single counters to 0 atomically.
    pub fn phasm_reset_hook_dual_counters();

    /// Single-write helper (HOOK-A/B/E) — total fires.
    pub fn phasm_get_hook_single_fires_total() -> u64;
    /// Single-write helper — bails on `*level == 0`.
    pub fn phasm_get_hook_single_bail_level_zero() -> u64;
    /// Single-write helper — successful applies.
    pub fn phasm_get_hook_single_applied() -> u64;
}

// ---------------------------------------------------------------------
// 12. Phasm encoder shim FFI (core/openh264-sys/shim/phasm_encoder_shim.h)
//
// Minimal C surface over the OpenH264 ISVCEncoder C++ class so Rust
// doesn't have to model the C++ vtable. Phasm-core consumers use the
// high-level `Encoder` wrapper in phasm_core::codec::h264::openh264;
// the raw FFI is exposed here for that wrapper's internal use only.
// ---------------------------------------------------------------------

/// Opaque encoder handle. Lifetime managed by phasm_encoder_create +
/// phasm_encoder_destroy.
#[repr(C)]
pub struct PhasmEncoderHandle {
    _opaque: [u8; 0],
}

/// Frame type returned by `phasm_encoder_encode_frame` on success.
#[allow(dead_code)]
pub const PHASM_FRAME_INVALID: i32 = 0;
pub const PHASM_FRAME_IDR: i32 = 1;
#[allow(dead_code)]
pub const PHASM_FRAME_I: i32 = 2;
pub const PHASM_FRAME_P: i32 = 3;
#[allow(dead_code)]
pub const PHASM_FRAME_SKIP: i32 = 4;
#[allow(dead_code)]
pub const PHASM_FRAME_IPMIXED: i32 = 5;

unsafe extern "C" {
    /// Create a new encoder. Returns null on failure.
    pub fn phasm_encoder_create() -> *mut PhasmEncoderHandle;

    /// Destroy an encoder. Safe to call with null. Idempotent.
    pub fn phasm_encoder_destroy(h: *mut PhasmEncoderHandle);

    /// Initialize with phasm's deterministic defaults at the given
    /// geometry and QP. Returns 0 on success, negative on error.
    pub fn phasm_encoder_initialize(
        h: *mut PhasmEncoderHandle,
        width: i32,
        height: i32,
        qp: i32,
        gop_size: i32,
    ) -> i32;

    /// Uninitialize (release internal buffers). Called automatically
    /// by destroy; only needed if re-initializing with new params.
    pub fn phasm_encoder_uninitialize(h: *mut PhasmEncoderHandle) -> i32;

    /// Encode one YUV 4:2:0 frame. Returns PHASM_FRAME_* on success,
    /// negative error code on failure (see shim header).
    pub fn phasm_encoder_encode_frame(
        h: *mut PhasmEncoderHandle,
        y_plane: *const u8,
        y_stride: i32,
        u_plane: *const u8,
        u_stride: i32,
        v_plane: *const u8,
        v_stride: i32,
        width: i32,
        height: i32,
        timestamp_msec: i64,
        out_buf: *mut u8,
        out_buf_capacity: i32,
        out_bytes_written: *mut i32,
    ) -> i32;

    /// C.9.0 (#482) — toggle dual_recon (pVisualRef[] mirror pool) before
    /// `phasm_encoder_initialize`. enabled=0 skips ALL visual_recon work
    /// for the next encoder instance; the resulting bitstream is byte-
    /// identical to the dual_recon-enabled run (mirror is encoder-internal
    /// only). Used by the Pass-1 cover probe + parallel-GOP clean producers.
    ///
    /// B-lite.2 (#891): the fork stores this flag `thread_local`, so each
    /// thread's encoder construction is independent — a producer thread
    /// setting 0 never disturbs the consumer thread's 1. Set it immediately
    /// before `phasm_encoder_initialize` on the SAME thread (the flag has a
    /// single read site at `InitDqLayers`, on the init thread).
    pub fn phasm_encoder_set_dual_recon_enabled(enabled: i32);

    /// B-lite.2 (#891) — read the CALLING thread's dual_recon flag (stored
    /// `thread_local` in the fork; defaults to 1). Used by the
    /// thread-isolation gate.
    pub fn phasm_get_dual_recon_enabled() -> i32;

    /// D2.1 — per-row completion callback for windowed STC.
    pub fn phasm_set_row_complete_callback(cb: Option<extern "C" fn(
        frame_num: u32, row_y: u16,
        bs_byte_pos: i32, bs_bits_left: i32,
    )>);

    /// P3.3b (2026-05-25) — post-quant coefficient capture callback.
    pub fn phasm_set_post_quant_callback(cb: Option<extern "C" fn(
        frame_num: u32, mb_x: u16, mb_y: u16,
        coeffs: *const i16, coeff_count: i32,
        cbp_luma: u8, cbp_chroma: u8, qp: i32,
    )>);
    /// P3.3b — replay mode: skip quantize, read from supplied buffer.
    pub fn phasm_set_coeff_replay_mode(enabled: i32);
    /// P3.3b — supply coefficient buffer for the next MB in replay mode.
    pub fn phasm_set_replay_coeffs(coeffs: *const i16, count: i32);
    /// P3.3b.4 — advance the replay pointer by `n` entries. Called
    /// automatically by WelsEncInterY after each MB; exposed here so
    /// Rust can also call it if needed (e.g. resetting between frames).
    pub fn phasm_advance_replay_coeffs(n: i32);

    /// P3.3a (2026-05-25) — get a mutable pointer to the OH264
    /// encoder's current pDecPic Y plane. Returns 0 on success,
    /// -1 if unavailable. The pointer is valid until the next
    /// `phasm_encoder_encode_frame` or encoder destruction.
    pub fn phasm_encoder_get_dec_pic_y(
        h: *mut PhasmEncoderHandle,
        y_ptr: *mut *mut u8,
        y_stride: *mut i32,
    ) -> i32;
}

// ---------------------------------------------------------------------
// 13. Phasm decoder shim FFI (core/openh264-sys/shim/phasm_decoder_shim.h)
//
// Minimal C surface over the OpenH264 ISVCDecoder C++ class so Rust
// doesn't have to model the C++ vtable. Phasm-core consumers use the
// high-level `Decoder` wrapper in phasm_core::codec::h264::openh264;
// the raw FFI is exposed here for that wrapper's internal use only.
//
// Phase B.9.1 ships the bare decode-to-YUV surface. The wels_stego
// `dec_post_read` callback is plumbed through the encoder TU only —
// fork-side patches that make the DECODER actually fire that callback
// are Phase B.9.2 (gated separately due to fork-modification risk).
// ---------------------------------------------------------------------

/// Opaque decoder handle. Lifetime managed by phasm_decoder_create +
/// phasm_decoder_destroy.
#[repr(C)]
pub struct PhasmDecoderHandle {
    _opaque: [u8; 0],
}

unsafe extern "C" {
    /// Create a new decoder. Returns null on failure.
    pub fn phasm_decoder_create() -> *mut PhasmDecoderHandle;

    /// Destroy a decoder. Safe to call with null. Idempotent.
    pub fn phasm_decoder_destroy(h: *mut PhasmDecoderHandle);

    /// Initialize with phasm's deterministic defaults. Returns 0 on
    /// success, negative on error. Equivalent to
    /// `phasm_decoder_initialize_with_options(h, 0)`.
    pub fn phasm_decoder_initialize(h: *mut PhasmDecoderHandle) -> i32;

    /// Initialize with options. `parse_only != 0` sets
    /// `SDecodingParam.bParseOnly = true`.
    ///
    /// WARNING — NOT compatible with phasm stego hooks. OpenH264's
    /// bParseOnly exits before residual decoding (decoder_core.cpp:89),
    /// so the `dec_post_read` callbacks (B.9.2.2-.5) do not fire under
    /// parse_only. Retained for SPS-metadata-only callers. See the
    /// negative-result test `b9_2_6_parse_only_skips_residual_parse`
    /// in `core/src/codec/h264/openh264.rs` for details.
    pub fn phasm_decoder_initialize_with_options(
        h: *mut PhasmDecoderHandle,
        parse_only: i32,
    ) -> i32;

    /// Uninitialize (release internal buffers). Called automatically
    /// by destroy; only needed for re-init on the same handle.
    pub fn phasm_decoder_uninitialize(h: *mut PhasmDecoderHandle) -> i32;

    /// Decode one Annex-B chunk into Y/U/V planes. Output pointers are
    /// owned by the decoder and remain valid until the next call.
    /// Returns 0 on success (check `*out_buffer_status == 1` for a
    /// ready frame), negative on error.
    pub fn phasm_decoder_decode_frame(
        h: *mut PhasmDecoderHandle,
        bytes: *const u8,
        len: i32,
        out_buffer_status: *mut i32,
        out_width: *mut i32,
        out_height: *mut i32,
        out_y_stride: *mut i32,
        out_uv_stride: *mut i32,
        out_y_plane: *mut *const u8,
        out_u_plane: *mut *const u8,
        out_v_plane: *mut *const u8,
    ) -> i32;

    /// Drain one frame from the decoder's reorder buffer (post-input).
    /// Same output semantics as `phasm_decoder_decode_frame`.
    pub fn phasm_decoder_flush_frame(
        h: *mut PhasmDecoderHandle,
        out_buffer_status: *mut i32,
        out_width: *mut i32,
        out_height: *mut i32,
        out_y_stride: *mut i32,
        out_uv_stride: *mut i32,
        out_y_plane: *mut *const u8,
        out_u_plane: *mut *const u8,
        out_v_plane: *mut *const u8,
    ) -> i32;

    /// Query how many frames remain in the decoder's reorder buffer
    /// after all input has been fed. Returns 0 on success.
    pub fn phasm_decoder_frames_remaining(
        h: *mut PhasmDecoderHandle,
        out_count: *mut i32,
    ) -> i32;
}

// ---------------------------------------------------------------------
// 11. Tests (compile-time + runtime sanity)
// ---------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn struct_sizes() {
        // Belt-and-suspenders: same checks as the const _ asserts
        // above, but accessible to the test runner for human eyes.
        assert_eq!(core::mem::size_of::<PhasmStegoPos>(), 16);
        assert_eq!(core::mem::size_of::<PhasmStegoMdCost>(), 20);
        // PhasmStegoCallbacks layout: usize + 3 fn pointers. On 64-bit
        // targets that's 8 + 8*3 = 32; on 32-bit it's 4 + 4*3 = 16.
        // We only assert it's a multiple of the pointer size.
        let cb_size = core::mem::size_of::<PhasmStegoCallbacks>();
        let ptr_size = core::mem::size_of::<*mut ()>();
        assert_eq!(cb_size % ptr_size, 0, "PhasmStegoCallbacks size {} not aligned to ptr size {}", cb_size, ptr_size);
    }

    #[test]
    fn domain_round_trip() {
        for raw in 0u8..4 {
            let d = PhasmStegoDomain::from_u8(raw).expect("known domain");
            assert_eq!(d as u8, raw);
        }
        assert!(PhasmStegoDomain::from_u8(4).is_none());
        assert!(PhasmStegoDomain::from_u8(255).is_none());
    }

    #[test]
    fn abi_version_link() {
        // Smoke test: the linked library's version constant matches our
        // header constant. Proves build.rs wired the static lib in.
        let version = unsafe { WelsStegoAbiVersion() };
        assert_eq!(version, PHASM_STEGO_ABI_VERSION);
    }

    #[test]
    fn default_callbacks_is_all_null() {
        let cbs = PhasmStegoCallbacks::default();
        assert_eq!(cbs.struct_size, core::mem::size_of::<PhasmStegoCallbacks>());
        assert!(cbs.enc_pre_emit.is_none());
        assert!(cbs.dec_post_read.is_none());
        assert!(cbs.md_cost_capture.is_none());
        assert!(cbs.dual_recon_observe.is_none());
    }

    #[test]
    fn register_null_callbacks() {
        // Registering NULL should succeed (resets to no hooks).
        let rv = unsafe { WelsRegisterPhasmStegoCallbacks(core::ptr::null(), core::ptr::null_mut()) };
        assert_eq!(rv, 0);
    }

    #[test]
    fn set_frame_num_smoke() {
        // No return; just verify the symbol links + doesn't crash.
        unsafe { WelsStegoSetFrameNum(0) };
        unsafe { WelsStegoSetFrameNum(42) };
    }
}
